"""empty message

Revision ID: 9aa19c655f49
Revises: 
Create Date: 2021-04-06 19:08:31.364047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aa19c655f49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bird_details', sa.Column('image_credit', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bird_details', 'image_credit')
    # ### end Alembic commands ###
